DIM-12345

diff --git a/.github/workflows/source_workflow.yml b/.github/workflows/source_workflow.yml
--- a/.github/workflows/source_workflow.yml
+++ b/.github/workflows/source_workflow.yml
@@ -13,6 +13,12 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
+      - name: Successful Step
+        run: echo "This step is successful"
+      - name: Failing Step
+        run: exit 1  # Deliberately fail this step
+      - name: Another Successful Step
+        run: echo "This step is also successful"I     
   trigger_new_workflow:
     runs-on: ubuntu-latest
     steps:
